import scrapy

from bs4 import BeautifulSoup
from scrapy.shell import inspect_response


class DeathGripsSpider(scrapy.Spider):
    name = 'blogspider'
    start_urls = [
        'http://genius.com/Death-grips-5d-lyrics',
        'http://genius.com/Death-grips-80808-lyrics',
        'http://genius.com/Death-grips-anne-bonny-lyrics',
        'http://genius.com/Death-grips-artificial-death-in-the-west-lyrics',
        'http://genius.com/Death-grips-bass-rattle-stars-out-the-sky-lyrics',
        'http://genius.com/Death-grips-bb-poison-lyrics',
        'http://genius.com/Death-grips-beware-lyrics',
        'http://genius.com/Death-grips-beyond-alive-lyrics',
        'http://genius.com/Death-grips-big-dipper-lyrics',
        'http://genius.com/Death-grips-big-house-lyrics',
        'http://genius.com/Death-grips-billy-not-really-lyrics',
        'http://genius.com/Death-grips-birds-lyrics',
        'http://genius.com/Death-grips-bitch-please-lyrics',
        'http://genius.com/Death-grips-black-dice-lyrics',
        'http://genius.com/Death-grips-black-google-annotated',
        'http://genius.com/Death-grips-blackjack-lyrics',
        'http://genius.com/Death-grips-black-quarterback-lyrics',
        'http://genius.com/Death-grips-blood-creepin-lyrics',
        'http://genius.com/Death-grips-bootleg-dont-need-your-help-lyrics',
        'http://genius.com/Death-grips-bottomless-pit-lyrics',
        'http://genius.com/Death-grips-bottomless-pit-tracklist-album-art-lyrics',
        'http://genius.com/Death-grips-break-up-note-annotated',
        'http://genius.com/Death-grips-bubbles-buried-in-this-jungle-lyrics',
        'http://genius.com/Death-grips-centuries-of-damn-lyrics',
        'http://genius.com/Death-grips-come-up-and-get-me-lyrics',
        'http://genius.com/Death-grips-culture-shock-lyrics',
        'http://genius.com/Death-grips-cut-throat-instrumental-lyrics',
        'http://genius.com/Death-grips-darko-drum-12-lyrics',
        'http://genius.com/Death-grips-day-loop-6-lyrics',
        'http://genius.com/Death-grips-death-grips-20-lyrics',
        'http://genius.com/Death-grips-death-grips-next-grips-lyrics',
        'http://genius.com/Death-grips-deathgripz-lyrics',
        'http://genius.com/Death-grips-deep-web-lyrics',
        'http://genius.com/Death-grips-double-helix-lyrics',
        'http://genius.com/Death-grips-eh-lyrics',
        'http://genius.com/Death-grips-face-melter-how-to-do-impossible-things-lyrics',
        'http://genius.com/Death-grips-feels-like-a-wheel-lyrics',
        'http://genius.com/The-bug-fuck-a-bitch-lyrics',
        'http://genius.com/Death-grips-fuck-me-out-lyrics',
        'http://genius.com/Death-grips-fuck-that-lyrics',
        'http://genius.com/Death-grips-full-moon-death-classic-lyrics',
        'http://genius.com/Death-grips-fyrd-up-lyrics',
        'http://genius.com/Death-grips-get-got-lyrics',
        'http://genius.com/Death-grips-giving-bad-people-good-ideas-lyrics',
        'http://genius.com/Death-grips-government-plates-lyrics',
        'http://genius.com/Death-grips-government-plates-tracklist-album-art-lyrics',
        'http://genius.com/Death-grips-guillotine-lyrics',
        'http://genius.com/Death-grips-hacker-lyrics',
        'http://genius.com/Death-grips-have-a-sad-cum-bb-lyrics',
        'http://genius.com/Death-grips-hot-head-lyrics',
        'http://genius.com/Death-grips-houdini-lyrics',
        'http://genius.com/Death-grips-hunger-games-lyrics',
        'http://genius.com/Death-grips-hustle-bones-lyrics',
        'http://genius.com/Death-grips-i-break-mirrors-with-my-face-in-the-united-states-lyrics',
        'http://genius.com/Death-grips-im-overflow-lyrics',
        'http://genius.com/Death-grips-inanimate-sensation-lyrics',
        'http://genius.com/Death-grips-interview-a-lyrics',
        'http://genius.com/Death-grips-interview-b-lyrics',
        'http://genius.com/Death-grips-interview-c-lyrics',
        'http://genius.com/Death-grips-interview-d-lyrics',
        'http://genius.com/Death-grips-interview-e-lyrics',
        'http://genius.com/Death-grips-interview-f-lyrics',
        'http://genius.com/Death-grips-ive-seen-footage-lyrics',
        'http://genius.com/Death-grips-i-want-it-i-need-it-death-heated-lyrics',
        'http://genius.com/Death-grips-klink-lyrics',
        'http://genius.com/Death-grips-known-for-it-lyrics',
        'http://genius.com/Death-grips-lil-boy-lyrics',
        'http://genius.com/Death-grips-lock-your-doors-lyrics',
        'http://genius.com/Death-grips-lord-of-the-game-lyrics',
        'http://genius.com/Death-grips-lost-boys-lyrics',
        'http://genius.com/Death-grips-more-than-the-fairy-lyrics',
        'http://genius.com/Death-grips-no-love-lyrics',
        'http://genius.com/Death-grips-no-love-deep-web-tracklist-artwork-lyrics',
        'http://genius.com/Death-grips-on-gp-lyrics',
        'http://genius.com/Death-grips-pop-lyrics',
        'http://genius.com/Death-grips-poser-killer-lyrics',
        'http://genius.com/Death-grips-pss-pss-lyrics',
        'http://genius.com/Death-grips-punk-weight-lyrics',
        'http://genius.com/Death-grips-ring-a-bell-lyrics',
        'http://genius.com/Death-grips-runway-a-lyrics',
        'http://genius.com/Death-grips-runway-d-lyrics',
        'http://genius.com/Death-grips-runway-e-lyrics',
        'http://genius.com/Death-grips-runway-e-2-lyrics',
        'http://genius.com/Death-grips-runway-e-3-lyrics',
        'http://genius.com/Death-grips-runway-h-lyrics',
        'http://genius.com/Death-grips-runway-h-2-lyrics',
        'http://genius.com/Death-grips-runway-j-lyrics',
        'http://genius.com/Death-grips-runway-n-lyrics',
        'http://genius.com/Death-grips-runway-n-2-lyrics',
        'http://genius.com/Death-grips-runway-n-3-lyrics',
        'http://genius.com/Death-grips-runway-t-lyrics',
        'http://genius.com/Death-grips-runway-w-lyrics',
        'http://genius.com/Death-grips-runway-y-lyrics',
        'http://genius.com/Death-grips-say-hey-kid-lyrics',
        'http://genius.com/Death-grips-spikes-lyrics',
        'http://genius.com/Death-grips-spread-eagle-cross-the-block-lyrics',
        'http://genius.com/Death-grips-stockton-lyrics',
        'http://genius.com/Death-grips-system-blower-lyrics',
        'http://genius.com/Death-grips-takyon-death-yon-lyrics',
        'http://genius.com/Death-grips-the-cage-lyrics',
        'http://genius.com/Death-grips-the-fever-aye-aye-lyrics',
        'http://genius.com/Death-grips-the-money-store-tracklist-album-art-lyrics',
        'http://genius.com/Death-grips-the-powers-that-b-lyrics',
        'http://genius.com/Death-grips-the-powers-that-b-track-list-album-art-lyrics',
        'http://genius.com/Death-grips-this-is-violence-now-dont-get-me-wrong-lyrics',
        'http://genius.com/Death-grips-three-bedrooms-in-a-good-neighborhood-lyrics',
        'http://genius.com/Death-grips-thru-the-walls-lyrics',
        'http://genius.com/Death-grips-trash-lyrics',
        'http://genius.com/Death-grips-true-vulture-bare-lyrics',
        'http://genius.com/Death-grips-turned-off-lyrics',
        'http://genius.com/Death-grips-two-heavens-lyrics',
        'http://genius.com/Death-grips-up-my-sleeves-lyrics',
        'http://genius.com/Death-grips-voila-lyrics',
        'http://genius.com/Death-grips-warping-lyrics',
        'http://genius.com/Death-grips-whammy-lyrics',
        'http://genius.com/Death-grips-whatever-i-want-fuck-whos-watching-lyrics',
        'http://genius.com/Death-grips-why-a-bitch-gotta-lie-lyrics',
        'http://genius.com/Death-grips-world-of-dogs-lyrics',
        'http://genius.com/Death-grips-you-might-think-he-loves-you-for-your-money-but-i-know-what-he-really-loves-you-for-its-your-brand-new-leopard-skin-pillbox-hat-lyrics',
        ]

    def parse(self, response):
        result = {
            'title': response.css('h1.song_header-primary_info-title::text').extract_first(),
            'lyric': response.xpath('//div[@class="song_body-lyrics"]/lyrics/p//text()').extract()
        }
        # inspect_response(response, self)
        yield result

